CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE "Addresses" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Street" character varying(150) NOT NULL,
    "Number" character varying(20) NOT NULL,
    "Complement" character varying(150),
    "Neighborhood" character varying(100) NOT NULL,
    "FederativeUnit" character(2) NOT NULL,
    "City" character varying(100) NOT NULL,
    "ZipCode" character varying(9) NOT NULL,
    CONSTRAINT "PK_Addresses" PRIMARY KEY ("Id")
);

CREATE TABLE "Vehicles" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "VehicleType" integer NOT NULL,
    "Brand" character varying(50) NOT NULL,
    "Model" character varying(50) NOT NULL,
    "Color" character varying(50) NOT NULL,
    "VehicleYear" integer,
    "Notes" character varying(200),
    CONSTRAINT "PK_Vehicles" PRIMARY KEY ("Id")
);

CREATE TABLE "Customers" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(100) NOT NULL,
    "BirthDate" date,
    "Cpf" character(11) NOT NULL,
    "Phone" character varying(15) NOT NULL,
    "Email" character varying(100) NOT NULL,
    "AddressId" integer NOT NULL,
    CONSTRAINT "PK_Customers" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Customers_Addresses_AddressId" FOREIGN KEY ("AddressId") REFERENCES "Addresses" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "CustomerVehicles" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "CustomerId" integer,
    "VehicleId" integer,
    CONSTRAINT "PK_CustomerVehicles" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_CustomerVehicles_Customers_CustomerId" FOREIGN KEY ("CustomerId") REFERENCES "Customers" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_CustomerVehicles_Vehicles_VehicleId" FOREIGN KEY ("VehicleId") REFERENCES "Vehicles" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Stays" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "CustomerVehicleId" integer,
    "LicensePlate" character varying(10) NOT NULL,
    "EntryDate" timestamp with time zone,
    "ExitDate" timestamp with time zone,
    "HourlyRate" numeric(18,2) NOT NULL,
    "TotalAmount" numeric(18,2),
    "StayStatus" integer NOT NULL,
    CONSTRAINT "PK_Stays" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Stays_CustomerVehicles_CustomerVehicleId" FOREIGN KEY ("CustomerVehicleId") REFERENCES "CustomerVehicles" ("Id") ON DELETE RESTRICT
);

CREATE INDEX "IX_Customers_AddressId" ON "Customers" ("AddressId");

CREATE INDEX "IX_CustomerVehicles_CustomerId" ON "CustomerVehicles" ("CustomerId");

CREATE INDEX "IX_CustomerVehicles_VehicleId" ON "CustomerVehicles" ("VehicleId");

CREATE INDEX "IX_Stays_CustomerVehicleId" ON "Stays" ("CustomerVehicleId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260815135913_InitialCreate', '10.0.10');

COMMIT;

