<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Parking.Domain\Parking.Domain.csproj" />
    <ProjectReference Include="..\..\src\Parking.Service\Parking.Service.csproj" />
  </ItemGroup>

</Project>
